### ISSUE TITLE
System.NotSupportedException erialization and deserialization of 'System.Type' instances are not supported. Path: $.ClassInfo.Members.MemberType.

### ISSUE THREAD

**Issue by robertgro** [DevExpress/XPO#72]
Hi folks,

at first, thank you for your effort. To reproduce the bug, follow the steps beneath:

1. Create a blank VS Project with the '**ASP.NET Core Web API**' template selected, _Configure HTTPS_ and _Use Controllers_ as well as _Enable OpenAPI support_ option checked

2. Add a simple custom model class which derives from the "PersistentBase" class, e.g.
```   
public class Customers : PersistentBase
    {
        public Customers(Session session) : base(session)
        {
        }
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
    }
```
    
4. Add a controller with a UnitOfWork injected via Dependency Injection and a UnitOfWork.Query\<T\> Get() Action, e.g.
```   
public class CustomersController : Controller
    {
        UnitOfWork _uow;

        public CustomersController(UnitOfWork uow)
        {
            _uow = uow;
        }
        [HttpGet("Get")]
        public IActionResult Get()
        {
            var items = _uow.Query<Customers>();
            return items == null ? NotFound() : Ok(items);
        }
```

5. Modify your Program.cs to configure the default unit of work accordingly _*_:

```
builder.Services.AddXpoDefaultUnitOfWork(true, options =>
    options
        .UseConnectionString(builder.Configuration.GetConnectionString("Default"))
        .UseAutoCreationOption(AutoCreateOption.DatabaseAndSchema)
        .UseEntityTypes(typeof(Customers))
);
```

_* This assumes you have already added a ConnectionString section to your appsettings.json_

6. Launch the process, send a GET request to the specified endpoint and receive the following exception:

> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported. Path: $.ClassInfo.Members.MemberType.
>  ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported.
>    at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
>    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
>    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> 
> HEADERS
> =======
> Accept: */*
> Connection: keep-alive
> Host: localhost:7236
> User-Agent: PostmanRuntime/7.32.3
> Accept-Encoding: gzip, deflate, br
> Postman-Token: a3fe24fa-85c2-4ab0-96f7-1cbe42c2b4b9
-----------------------------------------------------------------------------------------------
Did I forget something? Unfortunately I wasn't able to find a better example demonstrating the use of DevExpress.XPO with the latest VS Core API project templates.

**Comment by Kill4kan** [comment]
Hello Robert,

Thank you for reaching out. Please refer to the following help topic to learn how to configure JSON serialization of XPO objects in your service: [Create an ASP\.NET Core Web API CRUD Service](https://docs.devexpress.com/XPO/403008/connect-to-a-data-store/create-an-asp-net-core-web-api-crud-service).

Please note that you need an active DevExpress subscription for XPO technical support. You can find more details here: [Object\-Relational Mapping Library](https://www.devexpress.com/products/net/orm/). So, we kindly request that you ask your questions in our Support Center using your DevExpress account: https://supportcenter.devexpress.com/ticket/list

**Comment by robertgro** [comment]
> Hello Robert,
> 
> Thank you for reaching out. Please refer to the following help topic to learn how to configure JSON serialization of XPO objects in your service: [Create an ASP.NET Core Web API CRUD Service](https://docs.devexpress.com/XPO/403008/connect-to-a-data-store/create-an-asp-net-core-web-api-crud-service).
> 
> Please note that you need an active DevExpress subscription for XPO technical support. You can find more details here: [Object-Relational Mapping Library](https://www.devexpress.com/products/net/orm/). So, we kindly request that you ask your questions in our Support Center using your DevExpress account: https://supportcenter.devexpress.com/ticket/list

Hey @Kill4kan

thank you for your response and the link to your help article. I didn't know that I have to help "**ASP.NET Core runtime create and load XPO models correctly**" with a mandatory ConfigureJsonOptions and XpoMetadataProvider class. I copied the code from the https://github.com/DevExpress-Examples/xpo-json-serialization/blob/21.1.3%2B/CS/XpoSerialization/XPOJsonOptions.cs and added the necessary directives

```
builder.Services.AddHttpContextAccessor();
builder.Services.ConfigureOptions<ConfigureJsonOptions>();
```

to my Program.cs. Now it's working as intended
```
[
    {
        "ID": 1,
        "Name": "John Doe",
        "Address": "1234 Elm Street, Springfield, IL 62704",
        "Phone": "(217) 555-1234"
    },
    {
        "ID": 2,
        "Name": "Jane Smith",
        "Address": "5678 Oak Avenue, Chicago, IL 60601",
        "Phone": "(312) 555-5678"
    },
    {
        "ID": 3,
        "Name": "Bob Johnson",
        "Address": "9012 Maple Drive, Peoria, IL 61602",
        "Phone": "(309) 555-9012"
    }
]
```

I apologize. Next time I'll reach out to your Support Center directly, because my company has indeed an active DevExpress subscription running.
